USE soeasy;

CREATE TABLE IF NOT EXISTS GPIO_LIST ( pin INT(100) NOT NULL , value INT(100) NOT NULL , PRIMARY KEY (pin));

DELETE FROM GPIO_LIST;

INSERT INTO GPIO_LIST VALUES (3, 2);
INSERT INTO GPIO_LIST VALUES (5, 3);
INSERT INTO GPIO_LIST VALUES (7, 4);
INSERT INTO GPIO_LIST VALUES (8, 14);
INSERT INTO GPIO_LIST VALUES (10, 15);
INSERT INTO GPIO_LIST VALUES (11, 17);
INSERT INTO GPIO_LIST VALUES (12, 18);
INSERT INTO GPIO_LIST VALUES (13, 27);
INSERT INTO GPIO_LIST VALUES (15, 22);
INSERT INTO GPIO_LIST VALUES (16, 23);
INSERT INTO GPIO_LIST VALUES (18, 24);
INSERT INTO GPIO_LIST VALUES (19, 10);
INSERT INTO GPIO_LIST VALUES (21, 9);
INSERT INTO GPIO_LIST VALUES (22, 25);
INSERT INTO GPIO_LIST VALUES (23, 11);
INSERT INTO GPIO_LIST VALUES (24, 8);
INSERT INTO GPIO_LIST VALUES (26, 7);
INSERT INTO GPIO_LIST VALUES (29, 5);
INSERT INTO GPIO_LIST VALUES (31, 6);
INSERT INTO GPIO_LIST VALUES (32, 12);
INSERT INTO GPIO_LIST VALUES (33, 13);
INSERT INTO GPIO_LIST VALUES (35, 19);
INSERT INTO GPIO_LIST VALUES (36, 16);
INSERT INTO GPIO_LIST VALUES (37, 26);
INSERT INTO GPIO_LIST VALUES (38, 20);
INSERT INTO GPIO_LIST VALUES (40, 21);